version: "3"

services:
  app:
    container_name: gobank
    build: .
    ports:
      - "8000:8080"
    volumes:
      - ./data:/go/src/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"